version: "3.9"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes: # make sure give permission (chmod -R 777) to these folders
      - ~/Dropbox/calibre-web-config:/config
      - ~/Dropbox/Calibre:/books
    ports:
      - 8083:8083
    expose:
      - "8083"
    restart: unless-stopped
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    volumes:
      - ~/Dropbox/Calibre:/books
      - ~/Dropbox/kavita-server-config:/kavita/config
    environment:
      - TZ=America/New_York
    ports:
      - 5050:5000
    expose:
      - "5050"
    restart: unless-stopped
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - calibre-web
      - kavita
